### PR TITLE
Vario sound feedback implementation

### PR DESCRIPTION
**Pull request by Yenya**
Hello, Kuba,

this is my current vario sound feedback implementation. It needs more space allocated at various places (see the commit messages). It also contains several minor fixes. Feel free to cherry-pick the commits or merge the whole branch, and then make or suggest the memory layout changes.

Thanks!

-Yenya

### CODE REVIEW

**Comment by qba667** [comment]
@Yenya I have improved layout. Simply append code to sections starting with .mod_code_

`
.mod_25C8_277F                             0x1a7       0x25c8
.mod_SIGNATURE_2780                         0x10       0x2780
.mod_2790_27FF                              0x6f       0x2790
.reserved_main                               0xc       0x2800
.mod_code_5174_5353                         0xc0       0x5174
.reserved_after_code_5174_5353               0x4       0x5354
.mod_code_65C8_68A7                        0x260       0x65c8
.reserved_after_code_65C8_68A7               0x4       0x68a8
.reserved_after_code_in_display_method       0xe       0xc306
.mod_code_C9B0_CA4F                         0x9c       0xc9b0
.reserved_after_code_C9B0_CA4F               0x4       0xca50
.mod_code_D50C_D5F7                         0x38       0xd50c
.reserved_after_code_D50C_D5F7               0x4       0xd5f8
.mod_code_E140_E754                        0x5b4       0xe140
.reserved_after_code_E140_E754               0x4       0xe754
.mod_code_F66C_FF8F                        0x6a4       0xf66c
.mod_extraMenu                              0x4a       0xffb0
.reserved_checksum                           0x3       0xfffd
`
Free space mod_code_F66C_FF8F
0xFF8F  - 0xf66c  - 0x6a4 = 638 bytes 
Free space mod_code_E140_E754
0xE754  - 0xE140 - 0x5b4 = 96 bytes 
Free space mod_code_D50C_D5F7
0xD5F7 - 0xD50C - 0x38 = 179 bytes
... etc

Please check if you are still able to compile it.
Maybe tomorrow I will try to merge your changes.

**Comment by Yenya** [comment]
Hello, Kuba,

I have rebased the vario branch to your current work. Now I better understand the memory mapping. For the vario implementation, I rearranged some functions to different sections in order to get more space for my varioSensorsSelect() method (i.e. the setup menu) and for checkUserAlarms() function, to which I added the vario handling.

Please have a look at it, now I think it can be mergeable.

----

Maybe we should version the data stored in the modelConfStruct. When I connect the model first time, the custom alarms sensors and vario sensor are uninitialized, and until I set them all to None or to an existing sensor type, the Tx sometimes reboots. Or would it be feasible to hook up to the model change, so that we can sanitize the sensor IDs (and the whole modelConfStruct), if they are not sane before? I think it would be a waste of time to do such sanitization on every checkCustomAlarms() call.

There is one more thing that I do not understand: you read the long sensor value with this code:

`sensorValue = longSensors[sensorValue];`

But before this line, the sensorValue contains the return value of getSensorValue, not a sensor ID. Is this correct? Could it be the source of spurious reboots when configPtr->alarm[i].sensorID is not a defined sensor ID?

**Comment by qba667** [comment]
Hello @Yenya changes you made looks really good! I will check how it behaves in free time and merge them into master branch.

```c
int32_t sensorValue = getSensorValue(sensorID, 0, 0);
```
for uint16 sensors it will provide sensor value or value 0x8000 if sensor is not defined.
In case of 4 bytes sensors (longSensors) we should get back index of item in longSensors array.
Here I ensure that sensor ID was correct and index is not outside of array.
```c
if(sensorID >= IBUS_MEAS_TYPE_GPS_LAT && sensorID <= IBUS_MEAS_TYPE_S8a && sensorValue < SENSORS_ARRAY_LENGTH)
```
Check you have added also makes sense 
```c
sensorValue >= 0
```
but because sensorValue is int32_t and return value form getSensorValue should be uint16_t it should not be lower than 0.
So this should not cause the reboot. 

Reboot can be caused by watchdog if some blocking occurs - but this one can be possibly check by setting a break point in watchdog interrupt handler.
The other reason for reboot could be performing BL or BX to some incorrect memory address. 
But on another hand if clearing configuration helps it must be related to alarm method. I will try to check this one.

**Comment by qba667** [comment]
@Yenya maybe should add default config as byte array and add set factory defaults (memcpy). This should take not more than 25 bytes for code and 36 bytes for the data.

**Comment by Yenya** [comment]
@qba667: Even more simple solution would be to initialize the modelConfStruct with zeroes. This should work with user alarms, vario, maybe other data (please check). I have added the following commit:

https://github.com/qba667/FlySkyI6/pull/33/commits/33fd9038ed263285411fd155ae946af896ea1c78

Does it look sane for you?

Thanks for the explanation of return value of getSensorValue(). Should I add another commit removing the test for sensorValue >= 0 ?

**Comment by Yenya** [comment]
OK, thanks for the feedback. I have removed the last commit from this branch. I also removed the tests for sensorValue >= 0 from the vario implementation.

**Pull request merged**
